import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import { Flex, Text } from '@chakra-ui/react'
import Navbar from '../components/Navbar'
import ClockLoader from "react-spinners/ClockLoader";
import styles from '../styles/Layout.module.css'

function Layout({ children }) {

    const [loading, setLoading] = useState(false);

    useEffect(() => {
        setLoading(true)
        setTimeout(() => {
            setLoading(false)
        }, 6000);
    }, []);

    return (
        <>
            <Head>
                <title>Image Gallary</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" type="image/png" sizes="16x16" href="./icons8-xlarge-icons-color-16.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="./icons8-xlarge-icons-color-32.png" />
            </Head>
            {
                loading ?
                    <div className={styles.loading}>
                        <div className={styles.loadingTxt}>
                            <ClockLoader loading={loading} color={'white'} size={50} />
                            <Text color='white' fontSize={'2xl'} ml={'4'} textAlign={'center'} >Loading...
                            </Text>
                        </div>
                        <div>
                            <Text className={styles.headingTxt}>Theme Store</Text>
                        </div>
                    </div>
                    :
                    <Flex flexDir={['column', 'column', 'row']}>
                        <>
                            <Navbar />
                            {children}
                        </>
                    </Flex>
            }
        </>
    )
}

export default Layout
